# You can remove this action file if you dont want to add github actions to your repo

name: Test_Action_Name ## Replace it with your own action name
on: push
jobs:
  start:
    name: Send build started notif to slack
    runs-on: ubuntu-latest
    outputs:
      output1: steps.slack.outputs.message_id
    steps:
      # Will send notification when the build will start
      - id: slack 
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.1
        with:
          channel: build-notifs
          status: STARTING
          color: warning
        run: |
          echo env.message_id
  job1:
    name: Job 1 here ## Add your jobs steps here
    runs-on: ubuntu-latest 
    steps:
      - name: define job steps
        run: |
          echo Job1 done

  # Will send notification when the build will get succeeded
  status:
    name: Notify build status
    runs-on: ubuntu-latest
    needs: start
    strategy:
      fail-fast: false
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: message id
        run: |
            echo ${{ needs.start.outputs.output1  }}
      # Will send notification when the build will get succeeded
      - name: Check for success
        if: env.WORKFLOW_CONCLUSION != 'failure'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ needs.start.outputs.output1 }}
          channel: build-notifs
          status: SUCCESS
          color: good
      
      # Will send notification when the build will get failed
      - name: Check for fail
        if: env.WORKFLOW_CONCLUSION =='failure'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ needs.start.outputs.output1  }}
          channel: build-notifs
          status: FAILED
          color: danger